name: pwa
description: "PPC TODA PWA"
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.9.0
  lottie: ^3.2.0
  stacked: ^3.4.4
  georange: ^1.0.0
  pinch_zoom: ^2.0.1
  google_maps: ^8.1.1
  dash_chat_2: ^0.0.21
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  firebase_auth: ^5.7.0
  firebase_core: ^3.10.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.1
  carousel_slider: ^5.1.1
  pin_code_fields: ^8.0.1
  dio_http_cache_lts: ^0.4.2
  firebase_messaging: ^15.2.10
  image_picker_for_web: ^3.0.6
  rx_shared_preferences: ^4.0.0
  pull_to_refresh_flutter3: ^2.0.2
  singleton: ^0.0.3-nullsafety
  flutter_polyline_points: ^3.0.1
  flutter_typeahead: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/
    - assets/json/
    - assets/